version: "3.9"
services:
  backend:
    container_name: customer-management-backend
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - h2db
    ports:
      - "8080:8080"
  
  h2db:
    container_name: customer-management-h2db
    image: oscarfonts/h2
    ports:
      - "9092:9092"
      - "8082:8082"